config-version = 2

after-startup-command = []

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 5

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = true

persistent-workspaces = [
    '1', # Browser (school)
    '2', # Browser (personal)
    '3', # Terminal
    '4', # Notes
    '5', # Discord
    '6', # Music
    '7', # Facetime/Zoom
    '8',
    '9',
    '0', 
]

on-focus-changed = ['move-mouse window-lazy-center']

[exec.env-vars]
    PATH = '${HOME}/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[[on-window-detected]]
    if.app-name-regex-substring = """\
        Calendar|Finder|Find My|Mail|Maps|Messages|\
        Reminders|Stocks|System Settings|Thunderbird|\
        Weather"""
    check-further-callbacks = true
    run = ['layout floating']

[[on-window-detected]]
    if.app-id = 'org.mozilla.thunderbird'
    if.window-title-regex-substring = 'Reminder'
    run = ['exec-and-forget aerospace-thunderbird']

[[on-window-detected]]
    if.app-id = 'org.mozilla.firefox'
    if.during-aerospace-startup = true
    run = ['move-node-to-workspace 1', 'workspace 1']

[[on-window-detected]]
    if.app-id = 'org.mozilla.thunderbird'
    if.during-aerospace-startup = true
    run = ['move-node-to-workspace 2', 'workspace 2']

[[on-window-detected]]
    if.app-id = 'com.mitchellh.ghostty'
    if.during-aerospace-startup = true
    run = ['move-node-to-workspace 3', 'workspace 3']

[[on-window-detected]]
    if.app-id = 'md.obsidian'
    if.during-aerospace-startup = true
    run = ['move-node-to-workspace 4', 'workspace 4']

[[on-window-detected]]
    if.app-id = 'com.hnc.Discord'
    if.during-aerospace-startup = true
    run = ['move-node-to-workspace 5', 'workspace 5']

[[on-window-detected]]
    if.app-id = 'com.apple.Music'
    if.during-aerospace-startup = true
    run = ['move-node-to-workspace 6', 'workspace 6']

[[on-window-detected]]
    if.app-name-regex-substring = 'FaceTime|Screen Sharing|zoom\.us'
    run = ['move-node-to-workspace 7', 'workspace 7', 'layout floating']

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 8
    inner.vertical =   8
    outer.left =       8
    outer.bottom =     8
    outer.top =        8
    outer.right =      8

[mode.main.binding]
    cmd-ctrl-alt-m = 'exec-and-forget open /System/Applications/Messages.app'
    cmd-ctrl-alt-r = 'exec-and-forget open /System/Applications/Reminders.app'
    cmd-ctrl-alt-x = 'exec-and-forget open /System/Applications/System\ Settings.app'
    cmd-ctrl-alt-e = 'exec-and-forget open -na /Applications/Ghostty.app --args -e ranger'

    cmd-ctrl-alt-f = 'fullscreen'

    cmd-ctrl-alt-slash = 'layout tiles horizontal vertical'
    cmd-ctrl-alt-comma = 'layout accordion horizontal vertical'

    cmd-ctrl-alt-h = 'focus left'
    cmd-ctrl-alt-j = 'focus down'
    cmd-ctrl-alt-k = 'focus up'
    cmd-ctrl-alt-l = 'focus right'

    cmd-ctrl-alt-shift-h = 'move left'
    cmd-ctrl-alt-shift-j = 'move down'
    cmd-ctrl-alt-shift-k = 'move up'
    cmd-ctrl-alt-shift-l = 'move right'

    cmd-ctrl-alt-minus = 'resize smart -50'
    cmd-ctrl-alt-equal = 'resize smart +50'

    cmd-ctrl-alt-backtick = 'workspace `'
    cmd-ctrl-alt-0 = 'workspace 0'
    cmd-ctrl-alt-1 = 'workspace 1'
    cmd-ctrl-alt-2 = 'workspace 2'
    cmd-ctrl-alt-3 = 'workspace 3'
    cmd-ctrl-alt-4 = 'workspace 4'
    cmd-ctrl-alt-5 = 'workspace 5'
    cmd-ctrl-alt-6 = 'workspace 6'
    cmd-ctrl-alt-7 = 'workspace 7'
    cmd-ctrl-alt-8 = 'workspace 8'
    cmd-ctrl-alt-9 = 'workspace 9'

    cmd-ctrl-alt-shift-backtick = ['move-node-to-workspace `', 'workspace `']
    cmd-ctrl-alt-shift-0 = ['move-node-to-workspace 0', 'workspace 0', 'layout tiling']
    cmd-ctrl-alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1', 'layout tiling']
    cmd-ctrl-alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2', 'layout tiling']
    cmd-ctrl-alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3', 'layout tiling']
    cmd-ctrl-alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4', 'layout tiling']
    cmd-ctrl-alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5', 'layout tiling']
    cmd-ctrl-alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6', 'layout tiling']
    cmd-ctrl-alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7', 'layout tiling']
    cmd-ctrl-alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8', 'layout tiling']
    cmd-ctrl-alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9', 'layout tiling']

    cmd-ctrl-alt-semicolon = 'mode service'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # Reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    backspace = ['close-all-windows-but-current', 'mode main']

    # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
    #s = ['layout sticky tiling', 'mode main']

    cmd-ctrl-alt-shift-h = ['join-with left', 'mode main']
    cmd-ctrl-alt-shift-j = ['join-with down', 'mode main']
    cmd-ctrl-alt-shift-k = ['join-with up', 'mode main']
    cmd-ctrl-alt-shift-l = ['join-with right', 'mode main']
